linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/dklima/sleep_nomore)
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/dklima/sleep_nomore
  mnd:
    checks:
      - argument
      - case
      - condition
      - operation
      - return
      - assign
  govet:
    disable:
      - shadow
  lll:
    line-length: 140
  misspell:
    locale: US

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

  disable:
    - gochecknoglobals
    - gochecknoinits
    - depguard
    - stylecheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - funlen
        - dupl
        - unparam
    - path: main\.go
      linters:
        - mnd
      text: "Magic number"

run:
  timeout: 5m