name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        go-version: ['1.21', '1.22']
        arch: [amd64, arm64]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Get dependencies
      run: |
        go mod download
        go mod verify
    
    - name: Run tests
      run: go test -v -short -race -coverprofile=coverage.txt -covermode=atomic ./...
    
    - name: Run benchmarks
      run: go test -bench=. -benchmem ./...
    
    - name: Build binary
      env:
        GOOS: windows
        GOARCH: ${{ matrix.arch }}
      run: go build -ldflags="-H windowsgui -s -w" -o sleepnomore_${{ matrix.arch }}.exe main.go
    
    - name: Upload coverage to Codecov
      if: matrix.go-version == '1.21' && matrix.arch == 'amd64'
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.txt
        flags: unittests
        name: codecov-umbrella
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: sleepnomore-${{ matrix.go-version }}-${{ matrix.arch }}
        path: sleepnomore_${{ matrix.arch }}.exe

  lint:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    
    - name: Run gofmt
      run: |
        $output = gofmt -l .
        if ($output) {
          Write-Host "The following files need formatting:"
          Write-Host $output
          exit 1
        }
    
    - name: Run go vet
      run: go vet ./...
    
    - name: Install golangci-lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    
    - name: Run golangci-lint
      run: golangci-lint run --timeout=5m --config=.golangci.yml
    
    - name: Install gocyclo
      run: go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
    
    - name: Check cyclomatic complexity
      run: |
        $output = gocyclo -over 15 .
        if ($output) {
          Write-Host "Functions with high cyclomatic complexity:"
          Write-Host $output
        }
    
    - name: Install ineffassign
      run: go install github.com/gordonklaus/ineffassign@latest
    
    - name: Run ineffassign
      run: ineffassign ./...
    
    - name: Install misspell
      run: go install github.com/client9/misspell/cmd/misspell@latest
    
    - name: Run misspell
      run: misspell -error .